blank_issues_enabled: false
contact_links:
  - name: Dúvidas e Discussões
    url: https://github.com/dawilao/AgendaObras/discussions
    about: Utilize esta área para tirar dúvidas gerais ou sugerir melhorias para o AgendaObras.